### ISSUE TITLE
Agent fails when CATTLE_SERVER is exposed on different port (e.g. :8443)

### ISSUE THREAD

**Issue by rcreate** [rancher/system-agent#61]
We exposed rancher master on port 8443 for some reasons. When I try to create a new cluster on a fresh VM, the rancher-system-agent.service is not working - even if I add the port :8443 in the config.yaml.

I guess, you did not expect that some people change the port, rancher is working on.

**Comment by Oats87** [comment]
@rcreate What are the arguments you are passing to the install script when you are running it?

**Comment by Oats87** [comment]
@rcreate to follow up on this -- it has been over a year since this issue was originally filed. If you are still encountering this issue, please open a new one and link to this one with the requested information from above. We perform testing with Rancher and this system-agent all the time using custom ports, and have not had an issue with this.
